import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs/app-beta';

import { Navbar } from './components/Navbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next E-Commerce 13',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bodyClasses = clsx(inter.className, 'bg-slate-700');

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={bodyClasses}>
          <Navbar />
          <main className="bg-slate-700 h-screen p-16">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
